select * from customer;

--Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as total_revenue from customer
group by gender;


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount
from customer
where discount_applied='Yes' and purchase_amount>=(select AVG(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 
    item_purchased,
    ROUND(AVG(CAST(review_rating AS DECIMAL(10,2))), 2) AS [Average Product Rating]
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select round(AVG(purchase_amount),2) as average_purchase_amounts, shipping_type
 from customer
 where shipping_type in ('Express','Standard')
 group by shipping_type;


--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
	COUNT(customer_id) as total_customers,
	ROUND(avg(purchase_amount),2) as avg_spend, 
	round(SUM(purchase_amount),2) as total_revenue  
from customer
group by subscription_status
order by total_revenue desc;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 
    item_purchased,
    ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as (	
select customer_id, previous_purchases,
case 
	when previous_purchases= 1 THEN 'New'
	when previous_purchases between 1 and 10 then 'Returning'
	else 'Loyal'
	end as customers_segment
from customer)
select customers_segment,count(*) as no_of_customers from customer_type
group by customers_segment;

--Q8. What are the top 3 most purchased products within each category? 
 WITH item_count AS(
	select category,
	item_purchased as products,
	COUNT(customer_id) as total_orders,
	Row_number() over(partition by category order by count(customer_id) desc) as ranks
from customer
group by category, item_purchased
)
select category,products, total_orders from item_count
where ranks<=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
	COUNT(customer_id) as repeat_buyers
from customer
where previous_purchases>5 
group by subscription_status;


--Q10. What is the revenue contribution of each age group? 
 select age_group, round(sum(purchase_amount),2) as revenue
 from customer
 group by age_group
 order by revenue desc;

--Q.11 find each customer’s total spending and then display customers whose total spending is above the overall average spending.
WITH customer_spending AS (
	select customer_id, 
		   sum(purchase_amount) as total_spend 
	from customer
	group by customer_id
	)
select customer_id, total_spend
from customer_spending
where total_spend >(select AVG(total_spend) from customer_spending)
order by total_spend desc;
